---
title: "Untitled"
author: "Chaveneau Lucas"
date: "22/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=8,
                      fig.align='center', echo = TRUE,
                      warning=FALSE, message=FALSE)
```

```{r packages, include = FALSE}
library(ggplot2)
library(knitr)
library(latex2exp)
library(ggforce)
theme_set(theme_minimal())
```

## Essai 

```{r données simulées}
N=100
X <- sort(rnorm(N, 40, 200)) 
Y <- 1+ 1.3*X + rnorm(N, 0, 300)
plot(X, Y)
```


```{r calculs usuels}
var_X = (1/N) * sum((X - mean(X))^2)
var_Y = (1/N) * sum((Y - mean(Y))^2)
COV_XY = (1/N) * sum((X - mean(X))*(Y - mean(Y)))
CC_P = COV_XY/(sqrt(var_X * var_Y))
V_X_Y = var_X + var_Y - 2 * sqrt(var_X) * sqrt(var_Y)
```

```{r}
graph_cor <- ggplot()+
  
  ## FULL POSITIV CORR
  geom_rect(aes(xmin = - sqrt(var_X), ymin = -sqrt(var_X), xmax = sqrt(var_Y), ymax = sqrt(var_Y)),
            alpha = 0.2,
            fill = "blue"
            )+
  
  ## NO CORR
  
  geom_polygon(
    aes(
      x = c(0, -sqrt(var_X), sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y)), sqrt(var_Y)), 
      y = c(sqrt(var_Y), 0, - sqrt(var_X), sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y)))
      )
    )+
  
  
  ## FULL NEGATIVE CORR
  geom_rect(aes(xmin = 0, ymin = 0, xmax = sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y)), ymax = sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y))),
            fill = "red",
            alpha = 0.2
            )+
  
  ### Params
  theme(title = element_text(size=10, face="bold"), panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())+
  labs(x=" ", y = " ")+
  scale_x_continuous(breaks=NULL)+
  scale_y_continuous(breaks=NULL)
```

```{r}
graph_cor
```

```{r}
graph_cor <- ggplot()+
  geom_polygon(
    aes(
      x = c(0, -sqrt(var_X), sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y)), sqrt(var_Y)), 
      y = c(sqrt(var_Y), 0, - sqrt(var_X), sqrt(var_X + var_Y - 2 * sqrt(var_X * var_Y)))
      )
    )
graph_cor
```

