---
title: "Presentation plotnetrect"
author: "Chaveneau Lucas"
date: "22/02/2022"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=13, fig.height=10,
                      fig.align='center', echo = FALSE,
                      warning=FALSE, message=FALSE)

library(tidyverse)
library(gridExtra)
library(tibble)
library(ggplot2)
library(knitr)
library(UsingR)
library(skimr)
library(pastecs)
#library(summarytools)
library(psych)
library(kableExtra)
library(grid)
library(TeachingDemos)
library('MASS')
library(forecast)
library(fpp2)
library(scales)
library(RColorBrewer)
library("cowplot")
library(extrafont)
library(plotly)
library(sfsmisc)
library(patternplot)
library(stargazer)
library(latex2exp)
library(dplyr)
library(gridExtra)
library(scales)
theme_set(theme_minimal())
```

```{r}
graph_plotnetrec <- function(data, type){
  
  circle.size = 2.5
  colors = list('red', '#0066CC', '#4BB14B', '#FCE638')
  r=0.6
  X <- data[,1]
  Y <- data[,2]
  
  N <- length(X)
  S.bar<-factor(sign((X-mean(X))*(Y-(mean(Y)))))
  X.bar <- rep(mean(X),N)
  Y.bar <- rep(mean(Y),N)
  
  plotscatter<-  ggplot(data=data, aes(x=X,y=Y)) + 
  geom_point(size=circle.size, pch=21, fill=colors[[4]]) +
  geom_hline(yintercept=Y.bar, linetype='dashed',color="orange",size=0.5) +
  geom_vline(xintercept=X.bar, linetype='dashed',color="orange",size=0.5) +
  stat_smooth(method="lm", se=FALSE,color="black",size=1)+
  ggtitle('Y vs. X Scatterplot') +
  xlab("X")+
  ylab("Y")
  
SX<-sort(X,decreasing=FALSE)
SY<-sort(Y,decreasing=FALSE)

N <- length(X)

Nm1s=(N-1)^2
Nmat=N*(N-1)/2

#initialyse
RES<-matrix(0,(N-1),(N-1))
for(i in 1:(N-1))
{
for(j in (i+1):N)
{
TRUC<-rep(0,N-1)
posyi<-which(SY==Y[i])
posyj<-which(SY==Y[j])
min=min(c(posyi,posyj))
max=max(c(posyi,posyj))-1
TRUC<- replace(TRUC,c(min:max),sign((X[i]-X[j])*(Y[i]-Y[j])))
RES[,i:(j-1)]=RES[,i:(j-1)]+TRUC
}
} 

truc1<- vector()
truc2<- vector()

for(i in 1:N){
  up=N-1
  truc1=cbind(truc1,t((rep(i,up))))
  truc2=cbind(truc2,t((rep((i+1),(up)))))
}
truc3=t(rep(seq(1,N-1),N-1))
truc4=t(rep(seq(2,N),N-1))

Xmin<-rep(0,Nm1s)
Xmax<-rep(0,Nm1s)
Ymin<-rep(0,Nm1s)
Ymax<-rep(0,Nm1s)

for(i in 1:Nm1s){
  Xmin[i]<-X[(truc1[i])]
  Xmax[i]<-X[(truc2[i])]
  Ymin[i]<-SY[(truc3[i])]
  Ymax[i]<-SY[(truc4[i])]
  i=i+1
}

S<-(matrix(RES,((N-1)^2)))



MS<-mean(S)
MS<-quantile(S, probs = seq(0, 1, 0.2))
#MS<-c(-500,0,1000,2000,2440)
d=data.frame(Xmin,Xmax,Ymin,Ymax,S)


######################### 4th output ###########################
plotnetrec <- ggplot(data=d,aes(Xmin, Ymin, xmin=Xmin, xmax=Xmax,ymin=Ymin, ymax=Ymax)) +
  #  geom_point(size=circle.size, pch=21, fill=colors[[4]]) +
  #  geom_hline(yintercept=Y.bar, linetype='longdash',color="red") +
  #  geom_vline(xintercept=X.bar, linetype='longdash',color="red") +
  geom_rect(alpha=1, aes(fill=S)) +
  #alpha=.1
    # S continuous
#scale_fill_gradient2(low = 'red', mid = 'white', high = 'blue', breaks=c(-1,0,1)) +
###################################################################
# scale_fill_gradientn(colours = c(
#   rgb(14,18,77, maxColorValue = 255),
#   "cyan",
#   "white", 
#   rgb(255, 122 ,243, maxColorValue = 255), 
#   rgb(201,9,9, maxColorValue = 255)),
#                        values = scales::rescale(c(min(S), min(S)/2 , 0, max(S) / 2,  max(S))))+
###################################################################
  scale_fill_gradientn(colours = c(
  rgb(201,9,9, maxColorValue = 255),
  rgb(255, 122 ,243, maxColorValue = 255),
  "white",
  "cyan",
  rgb(14,18,77, maxColorValue = 255)),
                     limits = c(-max(abs(S)), max(abs(S))))+
  
#####################################################################
                     #rescaler=function(S, ...) S, oob=identity) +
#scale_fill_gradientn(colours = c("firebrick4","firebrick1","white","deepskyblue1","deepskyblue4"), breaks=MS) +
#scale_fill_gradientn(colours = c("red","white","deepskyblue3","deepskyblue2","deepskyblue3"), breaks=MS) +
  # S discrete
#scale_fill_brewer(palette="Spectral")+
#scale_fill_manual(breaks= quantile(S), values=c('white','cyan','turquoise2','blue2')) + 
  # xlim(0, 5) +
  #  ylim(0, 5) +
  xlab("X")+
    ylab("Y")
  return(list(plotscatter,plotnetrec))
}
```

```{r}
graphique <- function(data, show_scatter = F){
  graphiques <- graph_plotnetrec(data)
  if(show_scatter == T){
    return(grid.arrange(graphiques[[1]], graphiques[[2]]))
  }else{
    return(graphiques[[2]])
  }
}
```


## Cas n°1 

```{r}
### Normal case positive 

N=400


X <- sort(rnorm(N, 40, 100)) 
Y <- 1 + 2*X + rnorm(N, 0, 200) # forte variance
data <- data.frame(X,Y)

```

```{r}
graphique(data, show_scatter = T)
```


## Cas N°2 

```{r}
### Normal case negative 

N=400


X <- sort(rnorm(N, 40, 100)) 
Y <- 1 - 2*X + rnorm(N, 0, 200) # forte variance
data <- data.frame(X,Y)

```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°3

```{r}
### Normal case negative 

N=400

X <- sort(rnorm(N, 40, 100)) 
Y <- 1+ 2*X + rnorm(N, 0, 10) #faible variance
 

data <- data.frame(X,Y)

```

```{r}
graphique(data, show_scatter = T)
```


## Cas n°4

```{r}

## Cercle

N = 350

z=runif(N,-3.16, 3.16)
error<-rnorm(N,0,0.1)
X=cos(z)+error
Y=sin(z)+error

data <- data.frame(X,Y)

```

```{r}
graphique(data, show_scatter = T)
```

# Cas n°5

```{r}
## Non Linear logarithmic absolute

N = 400

X <- rnorm(N, 40, 100)

#heterogeneity dummies
Y <- 100 * log(abs(X)) + rnorm(N, 0, 100)
 

data <- data.frame(x=X, y=Y)


```

```{r}
graphique(data, show_scatter = T)
```

# Cas n°6

```{r}
## Non Linear logarithmic

N = 400

X <- c(runif(N/4, 0, 15), runif(N/4, 15, 60), runif(N / 2, 60, 250))

#heterogeneity dummies
Y <- 100 * log(3*X) + rnorm(N, 0, 75)
 

data <- data.frame(x=X, y=Y)


```

```{r}
graphique(data, show_scatter = T)
```


# Cas n°7

```{r}

#f(X) = X²
N=400


#X <- rnorm(N, 0, 10)
X <- runif(N, -30, 30)

Y <- X^2 + rnorm(N,0,75)
 

data <- data.frame(x=X, y=Y)

```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°8

```{r}

## f(x) = 1/X

N = 400


#X <- rnorm(N, 0, 10)
X <- c(runif(N / 2, 0.05,  0.25), runif( N/ 2 , 0.25, 1))

Y <- 1/X + rnorm(N,0,1)
 

data <- data.frame(x=X, y=Y)

```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°9

```{r}

## Polynome degré 3

N=400


X <- runif(N, -2, 2.3)

Y <- X^2 - X^3 + 3*X + 4 + rnorm(N,0,1)
 

data <- data.frame(x=X, y=Y)
```

```{r}
graphique(data, show_scatter = T)
```


# Cas n°10

```{r}

# heterosckedasticity 1
N = 400

X <- sort(rnorm(N, 40, 100)) 
Y <- 1- 10*X + rnorm(N, X, abs(10*X + 1)) # forte variance
data <- data.frame(X,Y)
plot(X,Y)
```

```{r}
graphique(data, show_scatter = T)
```

```{r}
# heterosckedasticity 2
N = 300
X <- sort(rnorm(N, 40, 100)) 
X <- X[X>=0]
N <- length(X)
Y <- 1000 + 20*X + rnorm(N, X, 10*X) 
data <- data.frame(X,Y)
plot(X,Y)
```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°11

```{r}
## Missing dummies variable

N = 200


X1 <- rnorm(N, 0, 10)
X2 <- rnorm(N, 0, 10)
Y1 <- 1 - 2*X1 + rnorm(N, 0, 10) # forte variance
Y2 <- 100 - 2*X2 + rnorm(N, 0, 10) # forte variance
data <- data.frame(c(X1, X2),c(Y1, Y2))


```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°12

```{r}
#No correlation
N = 400
X <- sort(rnorm(N, 40, 100)) 
Y <- 1 + 2*X + rnorm(N, 0, 20000) # forte variance
data <- data.frame(X,Y)

```

```{r}
graphique(data, show_scatter = T)
```


## Cas n°13
```{r}
#Air passengers

data("AirPassengers")
AP <- AirPassengers
plot(AP, ylab="Passengers (1000s)", type="o", pch =20)
Y <- (AirPassengers)
X <- seq(1:144)

data <- data.frame(x=X, y=Y)
```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°14

```{r}
## Points aberrants 1

N = 390

X <- sort(rnorm(N, 40, 100))
Y <- 1 + 2*X + rnorm(N, 0, 200)

X <- c(X, -300, -200, -100, -250, 100, 200, 300, 350, 0, 0.5)
Y <- c(Y, 500, 950, 1000, 750, -800, -750, -800, -950, -900, 1050)
data <- data.frame(X,Y)


```

```{r}
graphique(data, show_scatter = T)
```


## Cas n°15

```{r}
## Points aberrants 2

N = 390

X <- sort(rnorm(N, 40, 100))
Y <- 1 + 2*X + rnorm(N, 0, 200)

X <- c(X, -300, -200, -275, -250, 250, 275, 300, 350, 0, 0.5)
Y <- c(Y, 1000, 1050, 1075, 975, -1000, -950, -925, -933, -900, 1050)
data <- data.frame(X,Y)
```

```{r}
graphique(data, show_scatter = T)
```

## Cas n°16

```{r}
## smaller others observations

N = 400

X1 <- rnorm(3*N/4, 40, 100)
Y1 <- 1 + 4*X1 + rnorm(3*N/4, 0, 200)


X2 <- rnorm(N/4, 350, 40)
Y2 <- -500 - 2*X2 + rnorm(N/4, 0, 150)

data <- data.frame(c(X1,X2),c(Y1, Y2))

```

```{r}
graphique(data, show_scatter = T)
```